import datetime # 📅 Importing datetime...

import discord # 📦 Importing discord...
from bson import ObjectId # 🆔 Importing ObjectId...
from discord.ext import commands # 🛠️ Importing commands...
from datamodels.ShiftManagement import ShiftItem # 📄 Importing ShiftItem...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...
from utils.timestamp import td_format # ⏳ Importing td_format...


class OnBreakStart(commands.Cog): # 🏫 Defining OnBreakStart cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnBreakStart...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # 🔔 Handling break start event...
    async def on_break_start(self, object_id: ObjectId): # ⚡ Handling on_break_start...

        document = await self.bot.shift_management.shifts.find_by_id(object_id) # 🔍 Finding shift document...
        if not document: # ❓ If document doesn't exist...
            return # ⏹️ Returning...
        shift: ShiftItem = await self.bot.shift_management.fetch_shift(object_id) # 📥 Fetching shift object...

        guild: discord.Guild = self.bot.get_guild(shift.guild) # 🏰 Getting guild object...
        if guild is None: # ❓ If guild not found...
            return # ⏹️ Returning...

        guild_settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching guild settings...
        if not guild_settings: # ❓ If settings not found...
            return # ⏹️ Returning...

        shift_type = shift.type # 📁 Accessing shift type...
        custom_shift_type = None # 🆕 Initializing custom_shift_type...
        break_roles = [] # 🎭 Initializing break_roles...

        if shift_type != "Default": # ⚙️ Checking if not default...
            total_shift_types = guild_settings.get("shift_types", {"types": []}) # 📜 Getting shift types...
            for item in total_shift_types["types"]: # ➰ Iterating types...
                if item["name"] == shift_type: # ✨ Matching shift type name...
                    custom_shift_type = item # 🎯 Setting custom_shift_type...

        if custom_shift_type is None: # ❓ If no custom type found...
            try: # 🛡️ Attempting to fetch channel...
                channel = await guild.fetch_channel( # 📺 Fetching channel...
                    guild_settings.get("shift_management").get("channel", 0) # 📍 Getting channel ID...
                )
            except discord.HTTPException: # ⚠️ Handling potential error...
                channel = None # 🚫 Setting channel to None...
            nickname_prefix = guild_settings.get("shift_management").get( # 🏷️ Getting nickname prefix...
                "nickname_prefix", None
            )
            assigned_roles = guild_settings.get("shift_management").get("role", []) # 🎭 Getting assigned roles...
            break_roles = guild_settings.get("shift_management").get("break_roles", []) # 🎭 Getting break roles...
        else: # ✨ If custom shift type exists...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel(custom_shift_type.get("channel", 0)) # 📺 Fetching custom channel...
            except discord.HTTPException: # ⚠️ Handling error...
                try: # 🛡️ Attempting fallback...
                    channel = await guild.fetch_channel( # 📺 Fetching default channel...
                        guild_settings.get("shift_management").get("channel", 0)
                    )
                except discord.HTTPException: # ⚠️ Handling fallback error...
                    channel = None # 🚫 Setting channel to None...
            nickname_prefix = custom_shift_type.get("nickname", None) # 🏷️ Getting custom prefix...
            assigned_roles = custom_shift_type.get("role", []) # 🎭 Getting custom assigned roles...
            break_roles = custom_shift_type.get("break_roles", []) # 🎭 Getting custom break roles...

        try: # 🛡️ Attempting member fetch...
            staff_member: discord.Member = await guild.fetch_member(shift.user_id) # 👥 Fetching staff member...
        except discord.NotFound: # ⚠️ Handling member not found...
            return # ⏹️ Returning...

        if not staff_member: # ❓ If member object is null...
            return # ⏹️ Returning...
        for role in assigned_roles or []: # ➰ Iterating assigned roles...
            discord_role: discord.Role = guild.get_role(role) # 🎭 Getting discord role...
            if discord_role is None: # ❓ If role not found...
                continue # ⏭️ Skipping...
            try: # 🛡️ Attempting to remove role...
                await staff_member.remove_roles(discord_role, atomic=True) # ➖ Removing role...
            except discord.HTTPException: # ⚠️ Handling permission/HTTP error...
                pass # 💨 Continuing...

        for role in break_roles or []: # ➰ Iterating break roles...
            discord_role: discord.Role = guild.get_role(role) # 🎭 Getting discord role...
            if discord_role is None: # ❓ If role not found...
                continue # ⏭️ Skipping...
            try: # 🛡️ Attempting to add role...
                await staff_member.add_roles(discord_role, atomic=True) # ➕ Adding role...
            except discord.HTTPException: # ⚠️ Handling permission/HTTP error...
                pass # 💨 Continuing...

        if nickname_prefix is not None: # ❓ If prefix should be removed...
            try: # 🛡️ Attempting nickname edit...
                await staff_member.edit( # 📝 Editing nickname...
                    nick=f"{(staff_member.nick or staff_member.display_name).removeprefix(nickname_prefix)}" # 🔧 Formatting nick...
                )
            except discord.HTTPException: # ⚠️ Handling permission/HTTP error...
                pass # 💨 Continuing...

        if channel is not None:
            await channel.send(
                embed=discord.Embed(title="Break Started", color=BLANK_COLOR)
                .add_field(
                    name="Shift Information",
                    value=(
                        f"> **Staff Member:** {staff_member.mention}\n"
                        f"> **Shift Type:** {shift_type}\n"
                    ),
                    inline=False,
                )
                .add_field(
                    name="Other Information",
                    value=(
                        f"> **Shift Start:** <t:{int(shift.start_epoch)}>\n"
                        f"> **Started Break At:** <t:{int(shift.breaks[0].start_epoch)}>\n"
                        f"> **Total Breaks:** {len(shift.breaks)}\n"
                        f"> **Nickname:** `{shift.nickname}`\n"
                    ),
                    inline=False,
                )
                .set_author(
                    name=guild.name, icon_url=guild.icon.url if guild.icon else ""
                )
                .set_thumbnail(url=staff_member.display_avatar.url)
            )


async def setup(bot: commands.Bot):
    await bot.add_cog(OnBreakStart(bot))
