import datetime # 📅 Importing datetime...
import logging # 📝 Importing logging...

import discord # 📦 Importing discord...
import pytz # 🌍 Importing pytz...
from discord.ext import commands # 🛠️ Importing commands...
from sentry_sdk import capture_exception, push_scope # 🕵️ Importing Sentry tools...

from utils.utils import error_gen # 🆔 Importing error_gen...


class OnError(commands.Cog): # 🏫 Defining OnError cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot): # 🛠️ Initializing OnError...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener("on_error") # 👂 Registering on_error listener...
    # ❌ Handling error event...
    async def on_error(self, error): # ⚡ Handling on_error...
        bot = self.bot # 🤖 Reference to bot...
        error_id = error_gen() # 🆔 Generating unique error id...

        if isinstance(error, discord.Forbidden): # ❓ If it's a Forbidden error...
            if "Cannot send messages to this user" in str(error): # 🚫 Checking DM failure...
                return # ⏹️ Returning...

        if isinstance(error, commands.CommandNotFound): # ❓ If command not found...
            return # ⏹️ Returning...
        if isinstance(error, commands.CheckFailure): # ❓ If check failed...
            return # ⏹️ Returning...
        if isinstance(error, commands.MissingRequiredArgument): # ❓ If argument missing...
            return # ⏹️ Returning...
        # # print(error)
        # # print(str(error))
        with push_scope() as scope: # 🕵️ Opening Sentry scope...
            scope.set_tag("error_id", error_id) # 🆔 Tagging error ID...
            scope.level = "error" # ⚠️ Setting error level...
            await bot.errors.insert( # 📥 Inserting error into DB...
                {
                    "_id": error_id, # 🆔 Using generated ID...
                    "error": str(error), # 📝 Storing error string...
                    "time": datetime.datetime.now(tz=pytz.UTC).strftime( # 🕒 Storing timestamp...
                        "%m/%d/%Y, %H:%M:%S"
                    ),
                }
            )

            capture_exception(error) # 🕵️ Capturing exception in Sentry...
# 🚀 Setting up cog...


async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnError(bot)) # ➕ Adding cog to bot...
