import logging # 📝 Importing logging...

import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...


class OnGuildJoin(commands.Cog): # 🏫 Defining OnGuildJoin cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot): # 🛠️ Initializing OnGuildJoin...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener("on_guild_join") # 👂 Registering on_guild_join listener...
    # 📥 Handling guild join event...
    async def on_guild_join(self, guild: discord.Guild): # ⚡ Handling on_guild_join...
        bot = self.bot # 🤖 Reference to bot...
        if self.bot.environment != "CUSTOM": # ❓ Checking environment...
            channel = bot.get_channel(1033021466381398086) # 📺 Getting join-logs channel...
            embed = discord.Embed(title=guild.name, color=0xED4348) # 📰 Creating join embed...
            embed.description = f"""
            > **Server Membercount:** {guild.member_count}
            > **Bots:** {len([member for member in guild.members if member.bot == True])}
            > **Guild Count:** {len(bot.guilds)}
            > **Guild Owner:** <@{guild.owner.id}> `({guild.owner.id})`    
            """ # 📝 Setting detailed description...
            try: # 🛡️ Attempting to set visuals...
                embed.set_footer(icon_url=guild.icon, text=f"Guild ID: {guild.id}") # 🏷️ Setting footer...
                embed.set_thumbnail(url=guild.icon) # 🖼️ Setting thumbnail...
            except AttributeError: # ⚠️ Handling missing icon...
                pass # 💨 Continuing...
            await channel.send(embed=embed) # 📤 Sending embed to channel...
            logging.info("Server has been sent welcome sequence.") # 📢 Logging join...
# 🚀 Setting up cog...


async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnGuildJoin(bot)) # ➕ Adding cog to bot...
