import datetime # 📅 Importing datetime...
import logging # 📝 Importing logging...
import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...

logger = logging.getLogger(__name__) # 🕵️ Setting up logger...


class OnInfractionRevoke(commands.Cog): # 🏫 Defining OnInfractionRevoke cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot): # 🛠️ Initializing OnInfractionRevoke...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # 🔓 Handling infraction revoke event...
    async def on_infraction_revoke(self, infraction): # ⚡ Handling on_infraction_revoke...
        try: # 🛡️ Attempting execution...
            guild = self.bot.get_guild(infraction["guild_id"]) # 🏰 Getting guild...
            if not guild: # ❓ If guild not found...
                return # ⏹️ Returning...

            settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
            if not settings or "infractions" not in settings: # ❓ If settings missing...
                return # ⏹️ Returning...

            member = guild.get_member(infraction["user_id"]) # 👥 Getting member...
            if member: # ✨ If member is in server...
                if "roles_removed" in infraction: # ❓ If roles were removed...
                    roles_to_add = [] # 🆕 Initializing roles_to_add...
                    for role_id in infraction["roles_removed"]: # ➰ Iterating roles...
                        role = guild.get_role(int(role_id)) # 🎭 Getting role object...
                        if role and role not in member.roles: # ❓ If valid and not held...
                            roles_to_add.append(role) # ➕ Adding to list...
                    if roles_to_add: # ❓ If list not empty...
                        try: # 🛡️ Attempting to restore...
                            await member.add_roles( # ➕ Restoring roles...
                                *roles_to_add,
                                reason="Infraction revoked - restoring removed roles",
                            )
                            roles_modified = True # ✅ Marking modification...
                        except discord.HTTPException as e: # ⚠️ Handling error...
                            logger.error( # 📢 Logging failure...
                                f"Failed to restore roles for {member.id}: {e}"
                            )

                if "roles_added" in infraction: # ❓ If roles were added...
                    roles_to_remove = [] # 🆕 Initializing roles_to_remove...
                    for role_id in infraction["roles_added"]: # ➰ Iterating roles...
                        role = guild.get_role(int(role_id)) # 🎭 Getting role object...
                        if role and role in member.roles: # ❓ If valid and held...
                            roles_to_remove.append(role) # ➕ Adding to list...
                    if roles_to_remove: # ❓ If list not empty...
                        try: # 🛡️ Attempting removal...
                            await member.remove_roles( # ➖ Removing roles...
                                *roles_to_remove,
                                reason="Infraction revoked - removing added roles",
                            )
                            roles_modified = True # ✅ Marking modification...
                        except discord.HTTPException as e: # ⚠️ Handling error...
                            logger.error( # 📢 Logging failure...
                                f"Failed to remove added roles for {member.id}: {e}"
                            )

                infraction_config = next( # 🔍 Finding config for type...
                    (
                        inf
                        for inf in settings["infractions"]["infractions"]
                        if inf["name"] == infraction["type"]
                    ),
                    None,
                )

                if infraction_config and infraction_config.get( # ❓ If in-game perms affected...
                    "remove_ingame_perms", False
                ):
                    try: # 🛡️ Attempting perms restore...
                        roblox_info = await self.bot.bloxlink.find_roblox( # 🔍 Finding roblox id...
                            infraction["user_id"]
                        )
                        if roblox_info and "robloxID" in roblox_info: # ❓ If linked...
                            roblox_id = roblox_info["robloxID"] # 🆔 Getting ID...
                            if member: # ❓ If member valid...
                                await self.bot.prc_api.run_command( # 🎮 Modifying in-game perms...
                                    guild.id, f":mod {roblox_id}"
                                )
                    except Exception as e: # ⚠️ Handling API error...
                        logger.error(f"Failed to restore in-game permissions: {e}") # 📢 Logging error...

                if settings.get("infractions", {}).get("dm_on_revoke", True): # ❓ If DM enabled...
                    try: # 🛡️ Attempting DM...
                        embed = discord.Embed( # 📰 Creating notify embed...
                            title="Infraction Revoked", # 🏷️ Setting title...
                            description=f"One of your infractions in **{guild.name}** has been revoked.", # 📝 Setting description...
                            color=BLANK_COLOR, # 🎨 Setting color...
                        )
                        embed.add_field( # ➕ Adding details field...
                            name="Details",
                            value=(
                                f"> **Type:** {infraction['type']}\n"
                                f"> **Original Reason:** {infraction['reason']}\n"
                                f"> **Issued:** <t:{int(infraction['timestamp'])}:F>\n"
                                f"> **Revoked:** <t:{int(infraction['revoked_at'])}:F>"
                            ),
                            inline=False,
                        )
                        await member.send(embed=embed)
                    except discord.HTTPException:
                        pass

            if log_channel_id := settings.get("infractions", {}).get("log_channel"):
                if log_channel := guild.get_channel(int(log_channel_id)):
                    embed = discord.Embed(
                        title="Infraction Revoked",
                        color=BLANK_COLOR,
                        timestamp=datetime.datetime.now(),
                    )
                    embed.add_field(
                        name="Details",
                        value=(
                            f"> **User:** <@{infraction['user_id']}>\n"
                            f"> **Type:** {infraction['type']}\n"
                            f"> **Original Reason:** {infraction['reason']}\n"
                            f"> **Original Issuer:** <@{infraction.get('issuer_id', '0')}>\n"
                            f"> **Revoked By:** <@{infraction['revoked_by']}>\n"
                            f"> **Infraction ID:** `{infraction['_id']}`"
                        ),
                        inline=False,
                    )
                    await log_channel.send(embed=embed)

        except Exception as e:
            logger.error(f"Error in infraction revoke handler: {e}")


async def setup(bot):
    await bot.add_cog(OnInfractionRevoke(bot))
