import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...

from utils.constants import BLANK_COLOR, GREEN_COLOR # 🎨 Importing colors...


class OnLOAAccept(commands.Cog): # 🏫 Defining OnLOAAccept cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnLOAAccept...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # ✅ Handling LOA accept event...
    async def on_loa_accept(self, s_loa: dict, role_ids: list[int], accepted_by: int): # ⚡ Handling on_loa_accept...
        guild = self.bot.get_guild(s_loa["guild_id"]) # 🏰 Getting guild...
        try: # 🛡️ Attempting fetch...
            user = await guild.fetch_member(int(s_loa["user_id"])) # 👥 Fetching applicant member...
        except: # ⚠️ Handling fetch error...
            return # ⏹️ Returning...
        try: # 🛡️ Attempting notify...
            await user.send( # 📨 Sending DM...
                embed=discord.Embed( # 📰 Creating notify embed...
                    title=f"{self.bot.emoji_controller.get_emoji('success')} Activity Notice Accepted", # 🏷️ Setting title...
                    description=f"Your {s_loa['type']} request in **{guild.name}** was accepted!", # 📝 Setting description...
                    color=GREEN_COLOR, # 🎨 Setting color...
                )
            )
        except: # ⚠️ Handling DM blocked...
            pass # 💨 Continuing...

        settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
        loa_roles = list( # 🔍 Filtering valid roles...
            filter(
                lambda x: x is not None,
                [
                    discord.utils.get(guild.roles, id=identifier) # 🎭 Getting role by ID...
                    for identifier in role_ids
                ],
            )
        )
        for rl in loa_roles: # ➰ Iterating roles...
            if rl not in user.roles: # ❓ If role not already possessed...
                try: # 🛡️ Attempting add...
                    await user.add_roles(rl) # ➕ Adding role...
                except discord.HTTPException: # ⚠️ Handling permission/HTTP error...
                    pass # 💨 Continuing...

        msg = s_loa["message_id"] # 🆔 Getting original message ID...
        loa_channel_id = settings.get("staff_management", {}).get("channel", 0) # 📺 Getting LOA channel...
        if not loa_channel_id: # ❓ If channel not configured...
            return # ⏹️ Returning...
        loa_channel = guild.get_channel(loa_channel_id) or await guild.fetch_channel( # 📺 Getting channel object...
            loa_channel_id
        )
        messg = None # 🆕 Initializing messg variable...
        try: # 🛡️ Attempting fetch...
            messg = await loa_channel.fetch_message(msg) # 📩 Fetching request message...
        except: # ⚠️ Handling fetch failure...
            pass # 💨 Continuing...
        if not messg: # ❓ If message not found...
            return # ⏹️ Returning...

        embed = messg.embeds[0] # 📥 Accessing original embed...
        embed.title = ( # 🏷️ Updating title...
            f"{self.bot.emoji_controller.get_emoji('success')} {s_loa['type']} Accepted"
        )
        embed.colour = GREEN_COLOR # 🎨 Updating color...
        try: # 🛡️ Attempting issuer fetch...
            accepted_by_user = guild.get_member( # 👥 Getting acceptor...
                accepted_by
            ) or await guild.fetch_member(accepted_by)
        except: # ⚠️ Handling error...
            pass # 💨 Continuing...

        embed.set_footer( # 🏷️ Setting footer...
            text=f"Accepted by {accepted_by_user.name if accepted_by_user else 'n/a'}"
        )

        await messg.edit(embed=embed, view=None) # 📝 Editing message to final state...

        view_item = await self.bot.views.db.find_one({"message_id": messg.id}) # 🔍 Finding persistent view...

        await self.bot.views.delete_by_id(view_item["_id"]) # ➖ Deleting view from DB...


# 🚀 Setting up cog...
async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnLOAAccept(bot)) # ➕ Adding cog to bot...
