import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...

from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...


class OnLOADeny(commands.Cog): # 🏫 Defining OnLOADeny cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnLOADeny...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # ❌ Handling LOA deny event...
    async def on_loa_deny( # ⚡ Handling on_loa_deny...
        self, s_loa: dict, denied_by: int, reason: str = "No reason provided." # 📝 Defining parameters...
    ):
        guild = self.bot.get_guild(s_loa["guild_id"]) # 🏰 Getting guild...
        try: # 🛡️ Attempting fetch...
            user = await guild.fetch_member(int(s_loa["user_id"])) # 👥 Fetching applicant...
        except: # ⚠️ Handling fetch error...
            return # ⏹️ Returning...

        try: # 🛡️ Attempting notify...
            await user.send( # 📨 Sending DM...
                embed=discord.Embed( # 📰 Creating notify embed...
                    title="Activity Notice Denied", # 🏷️ Setting title...
                    description=f"Your {s_loa['type']} request in **{guild.name}** was denied.\n**Reason:** {reason}", # 📝 Setting description...
                    color=BLANK_COLOR, # 🎨 Setting color...
                )
            )
        except: # ⚠️ Handling DM blocked...
            pass # 💨 Continuing...

        settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
        msg = s_loa["message_id"] # 🆔 Getting message ID...
        loa_channel_id = settings.get("staff_management", {}).get("channel", 0) # 📺 Getting LOA channel...
        if not loa_channel_id: # ❓ If channel not configured...
            return # ⏹️ Returning...
        loa_channel = guild.get_channel(loa_channel_id) or await guild.fetch_channel( # 📺 Getting channel object...
            loa_channel_id
        )
        messg = None # 🆕 Initializing messg variable...
        try: # 🛡️ Attempting fetch...
            messg = await loa_channel.fetch_message(msg) # 📩 Fetching request message...
        except: # ⚠️ Handling fetch failure...
            pass # 💨 Continuing...
        if not messg: # ❓ If message not found...
            return # ⏹️ Returning...

        embed = messg.embeds[0] # 📥 Accessing original embed...
        embed.title = f"{s_loa['type']} Denied" # 🏷️ Updating title...
        embed.colour = BLANK_COLOR # 🎨 Updating color...
        try: # 🛡️ Attempting denier fetch...
            accepted_by_user = guild.get_member(denied_by) or await guild.fetch_member( # 👥 Fetching denier...
                denied_by
            )
        except: # ⚠️ Handling error...
            pass # 💨 Continuing...

        embed.set_footer( # 🏷️ Setting footer...
            text=f"Denied by {accepted_by_user.name if accepted_by_user else 'n/a'}"
        )

        await messg.edit(embed=embed, view=None) # 📝 Editing message to final state...

        view_item = await self.bot.views.db.find_one({"message_id": messg.id}) # 🔍 Finding persistent view...
        await self.bot.views.delete_by_id(view_item.id) # ➖ Deleting view from DB...


# 🚀 Setting up cog...
async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnLOADeny(bot)) # ➕ Adding cog to bot...
