import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
from erm import management_predicate, staff_predicate, management_check, staff_check # 🛡️ Importing predicates/checks...
import aiohttp # 🌐 Importing aiohttp...
from decouple import config # ⚙️ Importing config...


class OnMemberUpdate(commands.Cog): # 🏫 Defining OnMemberUpdate cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot): # 🛠️ Initializing OnMemberUpdate...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener("on_member_update") # 👂 Registering listener...
    # 🔄 Handling member update event...
    async def on_member_update(self, before, after): # ⚡ Handling on_member_update...
        if before.roles != after.roles: # ❓ If roles changed...
            # Roles have been changed
            old_permission = 0 # 🆕 Initializing old_permission...
            if await management_check(self.bot, before.guild, before): # ❓ If management...
                old_permission = 2 # ⬆️ Setting to management level...
            elif await staff_check(self.bot, before.guild, before): # ❓ If staff...
                old_permission = 1 # ⬆️ Setting to staff level...

            after_permission = 0 # 🆕 Initializing after_permission...
            if await management_check(self.bot, after.guild, after): # ❓ If management after...
                after_permission = 2 # ⬆️ Setting to management level...
            elif await staff_check(self.bot, after.guild, after): # ❓ If staff after...
                after_permission = 1 # ⬆️ Setting to staff level...

            if after_permission != old_permission: # ❓ If permission level changed...
                try: # 🛡️ Attempting update...
                    url_var = config("BASE_API_URL") # 🌐 Getting Base API URL...
                    if url_var in ["", None]: # ❓ If URL missing...
                        return # ⏹️ Returning...

                    panel_url_var = config("PANEL_API_URL") # 🌐 Getting Panel API URL...
                    if panel_url_var in ["", None]: # ❓ If URL missing...
                        return # ⏹️ Returning...

                    async with aiohttp.ClientSession() as session: # 🌐 Opening HTTP session...
                        async with session.get( # 📥 Calling auth cache update...
                            f"{url_var}/Auth/UpdatePermissionCache/{before.id}/{before.guild.id}/{after_permission}",
                            headers={"Authorization": config("INTERNAL_API_AUTH")},
                        ):
                            pass # 💨 Continuing...

                        url = f"{panel_url_var}/Internal/UpdatePermissionsCache/{before.guild.id}/{before.id}/{after_permission}" # 🔗 Internal URL...
                        print(f"Sending request to: {url}") # 📢 Printing log...

                        async with session.post(url): # 📥 Calling panel cache update...
                            pass # 💨 Continuing...

                except: # ⚠️ Catching errors...
                    pass # 💨 Continuing...


# 🚀 Setting up cog...
async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnMemberUpdate(bot)) # ➕ Adding cog to bot...
