import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
from erm import management_predicate, staff_predicate, management_check, staff_check # 🛡️ Importing predicates/checks...
import aiohttp # 🌐 Importing aiohttp...
from decouple import config # ⚙️ Importing config...


class OnMemberRemove(commands.Cog): # 🏫 Defining OnMemberRemove cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot): # 🛠️ Initializing OnMemberRemove...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener("on_member_remove") # 👂 Registering listener...
    # 📤 Handling member remove event...
    async def on_member_remove(self, member: discord.Member): # ⚡ Handling on_member_remove...
        try: # 🛡️ Attempting execution...
            url_var = config("BASE_API_URL") # 🌐 Getting Base API URL...
            if url_var in ["", None]: # ❓ If URL missing...
                return # ⏹️ Returning...

            panel_url_var = config("PANEL_API_URL") # 🌐 Getting Panel API URL...
            if panel_url_var in ["", None]: # ❓ If URL missing...
                return # ⏹️ Returning...

            async with aiohttp.ClientSession() as session: # 🌐 Opening HTTP session...
                async with session.get( # 📥 Calling auth cache update...
                    f"{url_var}/Auth/UpdatePermissionCache/{member.id}/{member.guild.id}/0",
                    headers={"Authorization": config("INTERNAL_API_AUTH")},
                ):
                    pass # 💨 Continuing...

                url = f"{panel_url_var}/Internal/UpdatePermissionsCache/{member.guild.id}/{member.id}/0" # 🔗 Internal URL...
                print(f"Sending request to: {url}") # 📢 Printing log...

                async with session.post(url): # 📥 Calling panel cache update...
                    pass # 💨 Continuing...

        except Exception as e: # ⚠️ Catching exceptions...
            print(f"l35, on_member_remove: {e}") # 📢 Printing error...


# 🚀 Setting up cog...
async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnMemberRemove(bot)) # ➕ Adding cog to bot...
