import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
from bson import ObjectId # 🆔 Importing ObjectId...
from roblox.client import Client # 🎮 Importing ROBLOX Client...
from datamodels.Warnings import WarningItem # 📄 Importing WarningItem...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...
import roblox # 🕹️ Importing roblox...


class OnPunishmentDelete(commands.Cog): # 🏫 Defining OnPunishmentDelete cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnPunishmentDelete...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # 🗑️ Handling punishment delete event...
    async def on_punishment_delete(self, objectid: ObjectId, manager: discord.Member): # ⚡ Handling on_punishment_delete...
        warning: WarningItem = await self.bot.punishments.fetch_warning(objectid) # 📥 Fetching punishment record...
        guild = self.bot.get_guild(warning.guild_id) # 🏰 Getting guild...
        if guild is None: # ❓ If guild not found...
            return # ⏹️ Returning...
        guild_settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
        if not guild_settings: # ❓ If settings missing...
            return # ⏹️ Returning...

        punishment_types = await self.bot.punishment_types.get_punishment_types( # ⚖️ Fetching types...
            warning.guild_id
        )

        warning_type = warning.warning_type # 🏷️ Accessing type...
        custom_warning_type = None # 🆕 Initializing custom_warning_type...
        if warning_type not in ["Warning", "Kick", "Ban", "BOLO"]: # ❓ If not standard type...
            for item in punishment_types["types"]: # ➰ Iterating types...
                if isinstance(item, dict): # ❓ If valid dictionary...
                    if item["name"] == warning_type: # ✨ Matching name...
                        custom_warning_type = item # 🎯 Setting custom type...

        if custom_warning_type is None: # ❓ If standard or not found...
            associations = { # 🗺️ Mapping types to channels...
                "warning": guild_settings.get("punishments").get("channel"),
                "kick": guild_settings.get("punishments").get("kick_channel"),
                "ban": guild_settings.get("punishments").get("ban_channel"),
                "bolo": guild_settings.get("punishments").get("bolo_channel"),
            }
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel( # 📺 Fetching associated channel...
                    associations[warning_type.lower().strip()]
                )
            except discord.HTTPException: # ⚠️ Handling fetch error...
                channel = None # 🚫 No channel...
        else: # ✨ If custom type was found...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel( # 📺 Fetching custom channel...
                    custom_warning_type.get("channel", 0)
                )
            except discord.HTTPException: # ⚠️ Handling error...
                try: # 🛡️ Attempting fallback...
                    channel = await guild.fetch_channel( # 📺 Fetching default...
                        guild_settings.get("shift_management").get("channel", 0)
                    )
                except discord.HTTPException: # ⚠️ Fallback failure...
                    channel = None # 🚫 No channel...

        try: # 🛡️ Attempting moderator fetch...
            moderator: discord.Member = guild.get_member(warning.moderator_id) # 👥 Fetching moderator...
        except discord.NotFound: # ⚠️ Handling moderator not in guild...
            return # ⏹️ Returning...

        if not moderator: # ❓ If moderator object null...
            return # ⏹️ Returning...
        roblox_client: Client = Client() # 🎮 Initializing ROBLOX client...
        roblox_user = await roblox_client.get_user(warning.user_id) # 👤 Fetching ROBLOX user...
        thumbnails = await roblox_client.thumbnails.get_user_avatar_thumbnails( # 🖼️ Fetching thumbnails...
            [roblox_user], type=roblox.thumbnails.AvatarThumbnailType.headshot
        )
        thumbnail = thumbnails[0].image_url # 🔗 Extracting thumbnail URL...

        if channel is not None: # ❓ If channel ready...
            return await channel.send( # 📤 Sending notify message...
                embed=discord.Embed(title="Punishment Revoked", color=BLANK_COLOR) # 📰 Creating revoke embed...
                .add_field( # ➕ Adding moderator info field...
                    name="Moderator Information",
                    value=(
                        f" **Moderator:** {moderator.mention}\n"
                        f" **Revoked By:** {manager.mention}\n"
                        f" **Warning ID:** `{warning.snowflake}`\n"
                        f" **Reason:** {warning.reason}\n"
                        f" **Moderated At:** <t:{int(warning.time_epoch)}>\n"
                    ),
                    inline=False,
                )
                .add_field( # ➕ Adding violator info field...
                    name="Violator Information",
                    value=(
                        f" **Username:** {warning.username}\n"
                        f" **User ID:** `{warning.user_id}`\n"
                        f"{'' if warning.until_epoch not in [None, 0] else ''} **Punishment Type:** {warning.warning_type}\n"
                        f"{' **Until:** <t:{}>'.format(int(warning.until_epoch)) if warning.until_epoch not in [None, 0] else ''}"
                    ),
                    inline=False,
                )
                .set_author(
                    name=guild.name, icon_url=guild.icon.url if guild.icon else ""
                )
                .set_thumbnail(url=thumbnail)
            )


async def setup(bot):
    await bot.add_cog(OnPunishmentDelete(bot))
