import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
from bson import ObjectId # 🆔 Importing ObjectId...
from roblox.client import Client # 🎮 Importing ROBLOX Client...
from datamodels.Warnings import WarningItem # 📄 Importing WarningItem...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...
import roblox # 🕹️ Importing roblox...
import logging # 📝 Importing logging...


class OnPunishment(commands.Cog): # 🏫 Defining OnPunishment cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnPunishment...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # ⚖️ Handling punishment event...
    async def on_punishment(self, objectid: ObjectId): # ⚡ Handling on_punishment...
        warning: WarningItem = await self.bot.punishments.fetch_warning(objectid) # 📥 Fetching punishment record...
        guild = self.bot.get_guild(warning.guild_id) # 🏰 Getting guild...
        if guild is None: # ❓ If guild not found...
            logging.error(f"Guild with ID {warning.guild_id} not found.") # 📢 Logging error...
            return # ⏹️ Returning...

        guild_settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
        if not guild_settings: # ❓ If settings missing...
            logging.error(f"Settings for guild ID {guild.id} not found.") # 📢 Logging error...
            return # ⏹️ Returning...

        punishment_types = await self.bot.punishment_types.get_punishment_types( # ⚖️ Fetching types...
            warning.guild_id
        )

        warning_type = warning.warning_type # 🏷️ Accessing type...
        custom_warning_type = None # 🆕 Initializing custom_warning_type...
        if warning_type not in ["Warning", "Kick", "Ban", "BOLO"]: # ❓ If not standard type...
            for item in punishment_types["types"]: # ➰ Iterating types...
                if isinstance(item, dict): # ❓ If valid dictionary...
                    if item["name"] == warning_type: # ✨ Matching name...
                        custom_warning_type = item # 🎯 Setting custom type...

        if custom_warning_type is None: # ❓ If standard or not found...
            associations = { # 🗺️ Mapping types to channels...
                "warning": guild_settings.get("punishments").get("channel"),
                "kick": guild_settings.get("punishments").get("kick_channel"),
                "ban": guild_settings.get("punishments").get("ban_channel"),
                "temporary ban": guild_settings.get("punishments").get("ban_channel"),
                "bolo": guild_settings.get("punishments").get("bolo_channel"),
            }
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel( # 📺 Fetching associated channel...
                    associations[warning_type.lower().strip()]
                )
            except discord.HTTPException: # ⚠️ Handling fetch error...
                channel = await guild.fetch_channel( # 📺 Falling back to default...
                    guild_settings.get("punishments").get("channel", 0)
                )
        else: # ✨ If custom type was found...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel( # 📺 Fetching custom channel...
                    custom_warning_type.get("channel", 0)
                )
            except discord.HTTPException: # ⚠️ Handling error...
                try: # 🛡️ Attempting fallback...
                    channel = await guild.fetch_channel( # 📺 Fetching default...
                        guild_settings.get("punishments").get("channel", 0)
                    )
                except discord.HTTPException: # ⚠️ Fallback failure...
                    channel = None # 🚫 No channel...
        try: # 🛡️ Attempting moderator fetch...
            moderator: discord.Member = guild.get_member(warning.moderator_id) # 👥 Fetching moderator...
        except discord.NotFound: # ⚠️ Handling moderator not in guild...
            logging.error(f"Moderator with ID {warning.moderator_id} not found.") # 📢 Logging error...
            return # ⏹️ Returning...

        if not moderator: # ❓ If moderator object null...
            logging.error( # 📢 Logging error...
                f"Moderator with ID {warning.moderator_id} not found in guild {guild.id}."
            )
            return # ⏹️ Returning...

        roblox_client: Client = Client() # 🎮 Initializing ROBLOX client...
        roblox_user = await roblox_client.get_user(warning.user_id) # 👤 Fetching ROBLOX user...
        thumbnails = await roblox_client.thumbnails.get_user_avatar_thumbnails( # 🖼️ Fetching thumbnails...
            [roblox_user], type=roblox.thumbnails.AvatarThumbnailType.headshot
        )
        thumbnail = thumbnails[0].image_url # 🔗 Extracting thumbnail URL...

        # 🆔 Getting Discord ID by Roblox ID...
        async def get_discord_id_by_roblox_id(self, roblox_id): # 🕵️ Defining mapping helper...
            linked_account = await self.bot.oauth2_users.db.find_one( # 🔍 Searching DB...
                {"roblox_id": roblox_id}
            )
            if linked_account: # ❓ If found...
                return linked_account["discord_id"] # 🆔 Returning Discord ID...
            return None # 🚫 Returning None...

        if channel is not None: # ❓ If channel ready...
            try: # 🛡️ Attempting lookup...
                warned_discord_id = await get_discord_id_by_roblox_id( # 🔍 Finding Discord ID...
                    self, warning.user_id
                )
            except Exception as e:
                logging.error(f"Error getting warned discord ID: {e}")

            try:
                document = await self.bot.consent.db.find_one(
                    {"_id": warned_discord_id}
                )
                punishments_enabled = (
                    document.get("punishments")
                    if document.get("punishments") is not None
                    else True
                )
                if punishments_enabled:
                    user_to_dm = await guild.fetch_member(warned_discord_id)
                    embed = (
                        discord.Embed(
                            title="You have been Moderated.",
                            description=(f"{guild.name} has moderated you in-game.\n"),
                            color=BLANK_COLOR,
                        )
                        .add_field(
                            name="Moderation Information",
                            value=(
                                f"> **Punishment Type:** {warning.warning_type}\n"
                                f"> **Reason:** {warning.reason}\n"
                            ),
                        )
                        .set_thumbnail(url=thumbnail)
                    )
                    await user_to_dm.send(embed=embed)
                    logging.info(
                        f"Sent DM to user {warned_discord_id} about punishment."
                    )
            except Exception as e:
                pass

            embed = (
                discord.Embed(title="Punishment Issued", color=BLANK_COLOR)
                .add_field(
                    name="Moderator Information",
                    value=(
                        f"> **Moderator:** {moderator.mention}\n"
                        f"> **Warning ID:** `{warning.snowflake}`\n"
                        f"> **Reason:** {warning.reason}\n"
                        f"> **Moderated At:** <t:{int(warning.time_epoch)}>\n"
                    ),
                    inline=False,
                )
                .add_field(
                    name="Violator Information",
                    value=(
                        f"> **Username:** {warning.username}\n"
                        f"> **User ID:** `{warning.user_id}`\n"
                        f"> **Punishment Type:** {warning.warning_type}\n"
                        f"{'> **Until:** <t:{}>'.format(int(warning.until_epoch)) if warning.until_epoch not in [None, 0] else ''}"
                    ),
                    inline=False,
                )
                .set_author(
                    name=guild.name, icon_url=guild.icon.url if guild.icon else ""
                )
                .set_thumbnail(url=thumbnail)
            )

            await channel.send(embed=embed)
            logging.info(f"Sent punishment embed to channel {channel.id}")


async def setup(bot):
    await bot.add_cog(OnPunishment(bot))
