import logging # 📝 Importing logging...
import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...

on_ready = False # 🏳️ Initializing on_ready flag...


class OnReady(commands.Cog): # 🏫 Defining OnReady cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot): # 🛠️ Initializing OnReady...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener("on_ready") # 👂 Registering on_ready listener...
    # 🏁 Handling ready event...
    async def on_ready(self): # ⚡ Handling on_ready...
        global on_ready # 🌍 Accessing global on_ready...
        if on_ready: # ❓ If on_ready is True...
            logging.info("{} has connected to gateway!".format(self.bot.user.name)) # 📢 Logging connection...
            on_ready = False # ⏹️ Resetting on_ready flag...

    @commands.Cog.listener("on_shard_connect") # 👂 Registering shard connect listener...
    # 💎 Handling shard connect event...
    async def on_shard_connect(self, sid: int): # ⚡ Handling shard connect...
        # 📞 Shard connection callback...
        async def callback(): # 📞 Defining internal callback...
            try: # 🛡️ Attempting fetch...
                channel = await self.bot.fetch_channel(1193390631192641687) # 📺 Fetching log channel...
                await channel.send( # 📤 Sending shard connect message...
                    embed=discord.Embed( # 📰 Creating embed...
                        title="Shard Connection", # 🏷️ Setting title...
                        description=f"Shard `{sid}` has connected.", # 📝 Setting description...
                        color=BLANK_COLOR, # 🎨 Setting color...
                    )
                )
            except Exception as e: # ⚠️ Catching any exception...
                # print(e)
                pass # 💨 Ignoring errors...

        # # # print('Shard connection')
        await callback() # 📞 Executing callback...

    @commands.Cog.listener("on_shard_disconnect") # 👂 Registering shard disconnect listener...
    # 🔌 Handling shard disconnect event...
    async def on_shard_disconnect(self, sid: int): # ⚡ Handling shard disconnect...
        # 📞 Shard disconnection callback...
        async def callback(): # 📞 Defining internal callback...
            try: # 🛡️ Attempting fetch...
                channel = await self.bot.fetch_channel(1193390631192641687) # 📺 Fetching log channel...
                await channel.send( # 📤 Sending shard disconnect message...
                    embed=discord.Embed( # 📰 Creating embed...
                        title="Shard Disconnection", # 🏷️ Setting title...
                        description=f"Shard `{sid}` has gracefully disconnected.", # 📝 Setting description...
                        color=BLANK_COLOR, # 🎨 Setting color...
                    )
                )
            except Exception as e: # ⚠️ Catching any exception...
                # # print(e)
                pass # 💨 Ignoring errors...

        # # # print('Shard disconnection')
        await callback() # 📞 Executing callback...


# 🚀 Setting up cog...
async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnReady(bot)) # ➕ Adding cog to bot...
