import discord # 📦 Importing discord...
from bson import ObjectId # 🆔 Importing ObjectId...
from discord.ext import commands # 🛠️ Importing commands...
from datamodels.ShiftManagement import ShiftItem # 📄 Importing ShiftItem...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...


class OnShiftStart(commands.Cog): # 🏫 Defining OnShiftStart cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnShiftStart...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # 🏁 Handling shift start event...
    async def on_shift_start(self, object_id: ObjectId): # ⚡ Handling on_shift_start...

        document = await self.bot.shift_management.shifts.find_by_id(object_id) # 🔍 Finding shift doc...
        if not document: # ❓ If doc missing...
            return # ⏹️ Returning...
        shift: ShiftItem = await self.bot.shift_management.fetch_shift(object_id) # 📥 Fetching shift object...

        guild: discord.Guild = self.bot.get_guild(shift.guild) # 🏰 Getting guild...
        if guild is None: # ❓ If guild not found...
            return # ⏹️ Returning...

        guild_settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
        if not guild_settings: # ❓ If settings missing...
            return # ⏹️ Returning...

        shift_type = shift.type # 🏷️ Getting shift type...
        custom_shift_type = None # 🆕 Initializing custom type...
        if shift_type != "Default": # ❓ If not default...
            total_shift_types = guild_settings.get("shift_types", {"types": []}) # 📜 Fetching types list...
            for item in total_shift_types["types"]: # ➰ Iterating types...
                if item["name"] == shift_type: # ✨ Matching name...
                    custom_shift_type = item # 🎯 Setting custom type...

        assigned_roles = [] # 🆕 Initializing assigned roles...
        if custom_shift_type is None: # ❓ If standard or not found...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel( # 📺 Fetching default channel...
                    guild_settings.get("shift_management").get("channel", 0)
                )
            except discord.HTTPException: # ⚠️ Handling error...
                channel = None # 🚫 No channel...
            nickname_prefix = guild_settings.get("shift_management").get( # 🏷️ Getting default prefix...
                "nickname_prefix", None
            )
            assigned_roles = guild_settings.get("shift_management").get("role", []) # 🎭 Getting default assigned roles...
        else: # ✨ If custom type found...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel(custom_shift_type.get("channel", 0)) # 📺 Fetching custom channel...
            except discord.HTTPException: # ⚠️ Handling error...
                try: # 🛡️ Attempting fallback...
                    channel = await guild.fetch_channel( # 📺 Fetching default...
                        guild_settings.get("shift_management").get("channel", 0)
                    )
                except discord.HTTPException: # ⚠️ Fallback error...
                    channel = None # 🚫 No channel...
            nickname_prefix = custom_shift_type.get("nickname", None) # 🏷️ Getting custom prefix...
            assigned_roles = custom_shift_type.get("role", []) # 🎭 Getting custom assigned roles...

        try: # 🛡️ Attempting member fetch...
            staff_member: discord.Member = await guild.fetch_member(shift.user_id) # 👥 Fetching staff member...
        except discord.NotFound: # ⚠️ Member not found...
            return # ⏹️ Returning...

        if not staff_member: # ❓ Member object null...
            return # ⏹️ Returning...

        guild_roles = await guild.fetch_roles() # 📜 Fetching all guild roles...
        for role in assigned_roles or []: # ➰ Iterating roles to add...
            discord_role: discord.Role = discord.utils.get(guild_roles, id=role) # 🎭 Finding role object...
            if discord_role is None: # ❓ If role missing...
                continue # ⏭️ Skipping...
            try: # 🛡️ Attempting to add role...
                await staff_member.add_roles(discord_role, atomic=True) # ➕ Adding role...
            except discord.HTTPException: # ⚠️ Handling permission/HTTP error...
                pass # 💨 Continuing...

        if nickname_prefix not in [None, "", "none"]: # ❓ If prefix should be applied...
            try: # 🛡️ Attempting nickname edit...
                await staff_member.edit( # 📝 Editing nickname...
                    nick=f"{nickname_prefix}{(staff_member.nick or staff_member.display_name)}" # 🔧 Formatting nick...
                )
            except discord.HTTPException: # ⚠️ Handling permission/HTTP error...
                pass # 💨 Continuing...

        if channel is not None: # ❓ If channel ready...
            await channel.send( # 📤 Sending start notification...
                embed=discord.Embed(title="Shift Started", color=BLANK_COLOR) # 📰 Creating start embed...
                .add_field( # ➕ Adding shift details...
                    name="Shift Information",
                    value=(
                        f"> **Staff Member:** {staff_member.mention}\n"
                        f"> **Shift Type:** {shift_type}\n"
                    ),
                    inline=False,
                )
                .add_field( # ➕ Adding field...
                    name="Other Information",
                    value=(
                        f"> **Shift Start:** <t:{int(shift.start_epoch)}>\n"
                        f"> **Nickname:** `{staff_member.nick}`\n"
                    ),
                    inline=False,
                )
                .set_author(
                    name=guild.name, icon_url=guild.icon.url if guild.icon else ""
                )
                .set_thumbnail(url=staff_member.display_avatar.url)
            )


async def setup(bot: commands.Bot):
    await bot.add_cog(OnShiftStart(bot))
