import typing # 📋 Importing typing...

import discord # 📦 Importing discord...
from bson import ObjectId # 🆔 Importing ObjectId...
from discord.ext import commands # 🛠️ Importing commands...
from datamodels.ShiftManagement import ShiftItem # 📄 Importing ShiftItem...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...


class OnShiftEdit(commands.Cog): # 🏫 Defining OnShiftEdit cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: commands.Bot): # 🛠️ Initializing OnShiftEdit...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # 📝 Handling shift edit event...
    async def on_shift_edit( # ⚡ Handling on_shift_edit...
        self,
        object_id: ObjectId, # 🆔 Identifying the shift...
        edited_attribute: typing.Literal["added_time", "removed_time"], # ✍️ Identifying what changed...
        editor: discord.Member, # 👥 Identifying the editor...
    ):

        document = await self.bot.shift_management.shifts.find_by_id(object_id) # 🔍 Finding shift doc...
        if not document: # ❓ If doc missing...
            return # ⏹️ Returning...
        shift: ShiftItem = await self.bot.shift_management.fetch_shift(object_id) # 📥 Fetching shift object...

        guild: discord.Guild = self.bot.get_guild(shift.guild) # 🏰 Getting guild...
        if guild is None: # ❓ If guild not found...
            return # ⏹️ Returning...

        guild_settings = await self.bot.settings.find_by_id(guild.id) # ⚙️ Fetching settings...
        if not guild_settings: # ❓ If settings missing...
            return # ⏹️ Returning...

        shift_type = shift.type # 🏷️ Getting shift type...
        custom_shift_type = None # 🆕 Initializing custom type...
        if shift_type != "Default": # ❓ If not default...
            total_shift_types = guild_settings.get("shift_types", {"types": []}) # 📜 Fetching types list...
            for item in total_shift_types["types"]: # ➰ Iterating types...
                if item["name"] == shift_type: # ✨ Matching name...
                    custom_shift_type = item # 🎯 Setting custom type...

        if custom_shift_type is None: # ❓ If standard or not found...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel( # 📺 Fetching default channel...
                    guild_settings.get("shift_management").get("channel", 0)
                )
            except discord.HTTPException: # ⚠️ Handling error...
                channel = None # 🚫 No channel...
        else: # ✨ If custom type found...
            try: # 🛡️ Attempting fetch...
                channel = await guild.fetch_channel(custom_shift_type.get("channel", 0)) # 📺 Fetching custom channel...
            except discord.HTTPException: # ⚠️ Handling error...
                try: # 🛡️ Attempting fallback...
                    channel = await guild.fetch_channel( # 📺 Fetching default...
                        guild_settings.get("shift_management").get("channel", 0)
                    )
                except discord.HTTPException: # ⚠️ Fallback error...
                    channel = None # 🚫 No channel...

        try: # 🛡️ Attempting member fetch...
            staff_member: discord.Member = await guild.fetch_member(shift.user_id) # 👥 Fetching staff member...
        except discord.NotFound: # ⚠️ Member not found...
            return # ⏹️ Returning...

        if not staff_member: # ❓ Member object null...
            return # ⏹️ Returning...
        if channel is not None: # ❓ If channel ready...
            await channel.send( # 📤 Sending edit notification...
                embed=discord.Embed(title="Shift Edited", color=BLANK_COLOR) # 📰 Creating edit embed...
                .add_field( # ➕ Adding staff info...
                    name="Shift Information",
                    value=(
                        f"> **Staff Member:** {staff_member.mention}\n"
                        f"> **Shift Type:** {shift_type}\n"
                    ),
                    inline=False,
                )
                .add_field( # ➕ Adding general info...
                    name="Other Information",
                    value=(
                        f"> **Shift Start:** <t:{int(shift.start_epoch)}>\n"
                        f"> **Nickname:** `{shift.nickname}`\n"
                    ),
                    inline=False,
                )
                .add_field( # ➕ Adding manager info...
                    name="Manager Information",
                    value=(
                        f"> **Edited By:** {editor.mention}\n"
                        f"> **Added Time:** `{shift.added_time}`\n"
                        if edited_attribute == "added_time"
                        else f"> **Removed Time:** `{shift.removed_time}`\n"
                    ),
                    inline=False,
                )
                .set_author( # 🏷️ Setting author...
                    name=guild.name, icon_url=guild.icon.url if guild.icon else ""
                )
                .set_thumbnail(url=staff_member.display_avatar.url)
            )


async def setup(bot: commands.Bot):
    await bot.add_cog(OnShiftEdit(bot))
