import aiohttp # 🌐 Importing aiohttp...
import discord # 📦 Importing discord...
from discord.ext import commands # 🛠️ Importing commands...
import bson # 🆔 Importing bson...
from erm import Bot # 🤖 Importing Bot class...
from bson import ObjectId # 🆔 Importing ObjectId...
from decouple import config # ⚙️ Importing config...

from menus import AcknowledgeStaffRequest # 📂 Importing menus...
from utils import prc_api # 🔌 Importing API utils...
from utils.constants import BLANK_COLOR # 🎨 Importing BLANK_COLOR...


class OnStaffRequestSend(commands.Cog): # 🏫 Defining OnStaffRequestSend cog...
    # ⚙️ Initializing cog...
    def __init__(self, bot: Bot): # 🛠️ Initializing OnStaffRequestSend...
        self.bot = bot # 🤖 Setting bot instance...

    @commands.Cog.listener() # 👂 Registering listener...
    # 📩 Handling staff request send event...
    async def on_staff_request_send(self, o_id: ObjectId): # ⚡ Handling on_staff_request_send...
        doc = await self.bot.staff_requests.db.find_one({"_id": o_id}) # 🔍 Finding request doc...
        user_id = doc["user_id"] # 🆔 Getting user ID...
        guild_id = doc["guild_id"] # 🏰 Getting guild ID...
        reason = doc["reason"] # 📝 Getting reason...

        settings = await self.bot.settings.db.find_one({"_id": guild_id}) # ⚙️ Fetching settings...
        staff_requests = settings.get("game_logging", {}).get("staff_requests", {}) # 📜 Accessing config...
        if staff_requests == {}: # ❓ If config empty...
            return # ⏹️ Returning...

        is_erlc = bool(await self.bot.server_keys.db.count_documents({"_id": guild_id})) # ❓ If ERLC server...
        players_ingame = -1 # 🔢 Initializing player count...
        staff_ingame = -1 # 🔢 Initializing staff count...
        if is_erlc: # ❓ If is ERLC...
            try: # 🛡️ Attempting fetch...
                players = await self.bot.prc_api.get_server_players(guild_id) # 👥 Fetching players...
            except prc_api.ResponseFailure: # ⚠️ Handling API failure...
                players = [] # 🚫 No players...

            if len(players) > 0: # ❓ If players active...
                players_ingame = len(players) # 🔢 Counting players...
                staff_ingame = len( # 👥 Counting staff...
                    list(filter(lambda x: x.permission != "Normal", players))
                )

        staff_clocked_in = await self.bot.shift_management.shifts.db.count_documents( # 🔢 Counting clocked in staff...
            {"EndEpoch": 0, "Guild": guild_id}
        )

        guild = self.bot.get_guild(guild_id) or await self.bot.fetch_guild(guild_id) # 🏰 Getting guild...
        user = guild.get_member(user_id) or await self.bot.fetch_user(user_id) # 👥 Getting user...
        newline = "\n" # 🆕 Defining newline...

        embed = ( # 📰 Creating request embed...
            discord.Embed(
                title="Staff Request Received", # 🏷️ Setting title...
                description="A new staff request has been received from <@{0}> ({0})".format( # 📝 Setting description...
                    user_id
                ),
                color=BLANK_COLOR, # 🎨 Setting color...
            )
            .set_thumbnail(url=user.display_avatar.url) # 🖼️ Setting thumbnail...
            .add_field( # ➕ Adding request info field...
                name="Request Information",
                value=(f"> **Reason:** {reason}\n" f"> **Requested By:** <@{user_id}>"),
                inline=False,
            )
            .add_field( # ➕ Adding staff info field...
                name="Staff Information",
                value=(
                    f"{'> **Players In-Game:** {0}{1}'.format(str(players_ingame), newline) if players_ingame > 0 else ''}"
                    f"> **Staff Clocked In:** {staff_clocked_in}\n"
                    f"{'> **Staff In-Game:** {0}{1}'.format(str(staff_ingame), newline) if staff_ingame > 0 else ''}"
                ),
            )
        )

        mentioned_roles = staff_requests.get("mentioned_roles", []) # 🎭 Getting mentioned roles...
        channel_id = staff_requests["channel"] # 📺 Getting channel ID...
        channel = guild.get_channel(channel_id) or await guild.fetch_channel(channel_id) # 📺 Getting channel...

        await channel.send( # 📤 Sending request notification...
            ", ".join(["<@&{0}>".format(role) for role in mentioned_roles]), # 📢 Pinging roles...
            embed=embed, # 📰 Sending embed...
            allowed_mentions=discord.AllowedMentions.all(), # 🔔 Allowing pings...
            view=AcknowledgeStaffRequest(self.bot, o_id), # 🔘 Adding interactive view...
        )


# 🚀 Setting up cog...
async def setup(bot): # 🛠️ Defining setup function...
    await bot.add_cog(OnStaffRequestSend(bot)) # ➕ Adding cog to bot...
